---
- name: Create a user on all servers
  hosts: servers
  tasks:
    - name: Create user
      user:
        name: Anu
        password: intelliqit
        uid: 2222
        shell: /bin/bash
        comment: "A normal user"

...
